services:
  - type: web
    name: rapid-saas-ai-store
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: .
    
    # Environment-specific settings
    scaling:
      minInstances: 1
      maxInstances: 10
      targetCPU: 70
      targetMemory: 80
    
    # Build settings
    buildFilter:
      paths:
        - "**/*.js"
        - "**/*.json"
        - "**/*.md"
        - "services/**"
        - "routes/**"
        - "middleware/**"
        - "config/**"
        - "utils/**"
      ignoredPaths:
        - "__tests__/**"
        - "docs/**"
        - "*.test.js"